### ISSUE TITLE
AttributeError: 'Workflow' object has no attribute 'overwrite_configfile'

### ISSUE THREAD

**Issue by TMiguelT** [4dn-dcic/tibanna#251]
Following the [SnakeMake](https://snakemake.readthedocs.io/en/stable/executable.html#executing-a-snakemake-workflow-via-tibanna-on-amazon-web-services) tutorial, I'm getting the following error as I try to run a pipeline:

```
$ snakemake --tibanna --default-remote-prefix=tibanna-genovic/test_data
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 9223372036854775807
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	2	call_variants
	1	combine_calls
	1	genotype_variants
	2	hard_filter_calls
	3	map_reads
	3	mark_duplicates
	1	merge_calls
	1	merge_variants
	1	multiqc
	1	plot_stats
	3	recalibrate_base_qualities
	3	samtools_stats
	2	select_calls
	1	snpeff
	2	trim_reads_pe
	1	trim_reads_se
	1	vcf_to_tsv
	30
running job using Tibanna...

[Tue Oct 15 13:04:57 2019]
rule trim_reads_pe:
    input: tibanna-genovic/test_data/data/reads/b.chr21.1.fq, tibanna-genovic/test_data/data/reads/b.chr21.2.fq
    output: tibanna-genovic/test_data/trimmed/B-1.1.fastq.gz, tibanna-genovic/test_data/trimmed/B-1.2.fastq.gz, tibanna-genovic/test_data/trimmed/B-1.1.unpaired.fastq.gz, tibanna-genovic/test_data/trimmed/B-1.2.unpaired.fastq.gz, tibanna-genovic/test_data/trimmed/B-1.trimlog.txt
    log: tibanna-genovic/test_data/logs/trimmomatic/B-1.log
    jobid: 25
    wildcards: sample=B, unit=1
    resources: mem_mb=3684, disk_mb=3684

Traceback (most recent call last):
  File "/tmp/tmp.1BY3tqvG9v/venv/lib/python3.6/site-packages/snakemake/__init__.py", line 611, in snakemake
    export_cwl=export_cwl,
  File "/tmp/tmp.1BY3tqvG9v/venv/lib/python3.6/site-packages/snakemake/workflow.py", line 775, in execute
    success = scheduler.schedule()
  File "/tmp/tmp.1BY3tqvG9v/venv/lib/python3.6/site-packages/snakemake/scheduler.py", line 365, in schedule
    self.run(job)
  File "/tmp/tmp.1BY3tqvG9v/venv/lib/python3.6/site-packages/snakemake/scheduler.py", line 384, in run
    error_callback=self._error,
  File "/tmp/tmp.1BY3tqvG9v/venv/lib/python3.6/site-packages/snakemake/executors.py", line 1829, in run
    tibanna_input = self.make_tibanna_input(job)
  File "/tmp/tmp.1BY3tqvG9v/venv/lib/python3.6/site-packages/snakemake/executors.py", line 1812, in make_tibanna_input
    self.add_workflow_files(job, tibanna_args)
  File "/tmp/tmp.1BY3tqvG9v/venv/lib/python3.6/site-packages/snakemake/executors.py", line 1723, in add_workflow_files
    self.workflow.overwrite_configfile, snakemake_dir
AttributeError: 'Workflow' object has no attribute 'overwrite_configfile'
```

**Comment by SooLee** [comment]
@TMiguelT Thank you for reporting this. We're working on it.

**Comment by TMiguelT** [comment]
Sorry, I had mixed up the title of this with another (unrelated) issue I was having

**Comment by TMiguelT** [comment]
I realise I should probably have put this issue in the SnakeMake repo, but thanks for doing that!
