### ISSUE TITLE
AttributeError: 'module' object has no attribute 'TemporaryDirectory'

### ISSUE THREAD

**Issue by sengoku93** [4dn-dcic/tibanna#254]
Hi,

When installing Tibanna and running tibanna deploy_unicorn --usergroup=test this error pops up:

setting up tibanna usergroup environment on AWS...
WARNING: Without setting buckets (using --buckets),Tibanna would have access to only public buckets.To give permission to Tibanna for private buckets,use --buckets=<bucket1>,<bucket2>,...
creating iam permissions with tibanna policy prefix tibanna_test
No handlers could be found for logger "tibanna.utils"
Tibanna usergroup test has been created on AWS.
creating a new step function... tibanna_unicorn_test
deploying lambdas...
preparing for deploy...
name=check_task_awsem
role_arn=arn:aws:iam::558013456147:role/tibanna_test_check_task_awsem
Traceback (most recent call last):
  File "/usr/bin/tibanna", line 11, in <module>
    load_entry_point('tibanna==0.10.2', 'console_scripts', 'tibanna')()
  File "/usr/lib/python2.7/site-packages/tibanna-0.10.2-py2.7.egg/tibanna/__main__.py", line 412, in main
    subcommandf(*sc_args)
  File "/usr/lib/python2.7/site-packages/tibanna-0.10.2-py2.7.egg/tibanna/__main__.py", line 285, in deploy_unicorn
    usergroup=usergroup, do_not_delete_public_access_block=do_not_delete_public_access_block)
  File "/usr/lib/python2.7/site-packages/tibanna-0.10.2-py2.7.egg/tibanna/core.py", line 778, in deploy_unicorn
    do_not_delete_public_access_block=do_not_delete_public_access_block)
  File "/usr/lib/python2.7/site-packages/tibanna-0.10.2-py2.7.egg/tibanna/core.py", line 769, in deploy_tibanna
    self.deploy_core('all', suffix=suffix, usergroup=usergroup)
  File "/usr/lib/python2.7/site-packages/tibanna-0.10.2-py2.7.egg/tibanna/core.py", line 711, in deploy_core
    self.deploy_lambda(name, suffix, usergroup)
  File "/usr/lib/python2.7/site-packages/tibanna-0.10.2-py2.7.egg/tibanna/core.py", line 699, in deploy_lambda
    extra_config=extra_config)
  File "/home/ec2-user/NGS_software/tibanna/.eggs/python_lambda_4dn-0.12.3-py2.7.egg/aws_lambda/aws_lambda.py", line 84, in deploy_function
    with tempfile.TemporaryDirectory() as tmp_dir:
AttributeError: 'module' object has no attribute 'TemporaryDirectory'

Any suggestions? Thank you

**Comment by SooLee** [comment]
Hi @sengoku93, I think the issue is python2.7. Do you mind trying with python 3.6? We don't support python 2.7 any more.

**Comment by sengoku93** [comment]
I was using python 3.7 but for some reason Tibanna installed in python2.7 directory. Problem is resolved. Thanks
