### ISSUE TITLE
Error running tibanna commands

### ISSUE THREAD

**Issue by nate-d-olson** [4dn-dcic/tibanna#260]
Hi I'm trying to use tibanna to run snakemake pipelines on AWS. I get the following error message when I try running any tibanna command, including `tibanna -v`. 

```
(smk_tibanna) PN119683:reference_genomes nolson$ tibanna -v
Traceback (most recent call last):
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/httpsession.py", line 263, in send
    chunked=self._chunked(request.headers),
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/urllib3/util/retry.py", line 376, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7fc4007b50b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/tibanna/vars.py", line 8, in <module>
    AWS_ACCOUNT_NUMBER = boto3.client('sts').get_caller_identity().get('Account')
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/client.py", line 272, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/client.py", line 563, in _make_api_call
    operation_model, request_dict, request_context)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/client.py", line 582, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/endpoint.py", line 244, in _send
    return self.http_session.send(request)
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/botocore/httpsession.py", line 283, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://sts.us-east-1a.amazonaws.com/"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nolson/anaconda3/envs/smk_tibanna/bin/tibanna", line 5, in <module>
    from tibanna.__main__ import main
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/tibanna/__main__.py", line 10, in <module>
    from .core import API
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/tibanna/core.py", line 16, in <module>
    from .vars import (
  File "/Users/nolson/anaconda3/envs/smk_tibanna/lib/python3.6/site-packages/tibanna/vars.py", line 10, in <module>
    raise Exception("Cannot find AWS_ACCOUNT_NUMBER: %s" % e)
Exception: Cannot find AWS_ACCOUNT_NUMBER: Could not connect to the endpoint URL: "https://sts.us-east-1a.amazonaws.com/"
```

Any help troubleshooting this error would is appreciated. 

Thanks
Nate

**Comment by SooLee** [comment]
```export AWS_ACCESS_KEY_ID=<AWS_ACCKESS_KEY>
export AWS_SECRET_ACCESS_KEY=<AWS_SECRET_KEY>
export AWS_DEFAULT_REGION=<AWS_REGION>
```

**Comment by SooLee** [comment]
I also released `0.11.2` just now that gives you a more informative error message when AWS credentials are not found.

**Comment by nate-d-olson** [comment]
Thanks, exporting the variables worked. The issue for me was that my institution uses SAML, https://aws.amazon.com/identity/saml/, to generate temporary access codes. As a result, my `.aws/credentials` has two profiles, one default which is blank and one generated using my institutions SAML script. When using the aws cli, I need to specify the profile using the `—profile` argument. Would it be possible to add this argument to the relevant tibanna commands? Probably not necessary but a nice feature for some edge case users.

**Comment by nate-d-olson** [comment]
Closing as issue was addressed
