### ISSUE TITLE
Jobs sometimes fail to finish after completing execution

### ISSUE THREAD

**Issue by nhartwic** [4dn-dcic/tibanna#307]
Apologies for the imprecise title. I'm currently running into an issue with one of my Snakemake workflows, specifically relating to a Busco analysis. The job starts correctly. Based on the logs, busco seems to run correctly. And then when busco stops running, the ec2 instance keeps running for many hours. [Here is a link to plotted metrics for an example failed job.](https://salk-tm-logs.s3.amazonaws.com/50GqmF8999zs.metrics/metrics.html) Cloudwatch logs contain the expected EC2 idle exception.

```
Nothing has been running for the past hour for job 50GqmF8999zs,but cannot terminate the instance - cpu utilization (0.994791666668486) : Nothing has been running for the past hour for job 50GqmF8999zs,(CPU utilization 0.994791666668486 and EBS read  bytes).: EC2IdleException
Traceback (most recent call last):
  File "/var/task/service.py", line 19, in handler
    return check_task(event)
  File "/var/task/tibanna/check_task.py", line 33, in check_task
    return CheckTask(input_json).run()
  File "/var/task/tibanna/check_task.py", line 124, in run
    cw_res['max_ebs_read_bytes'])
  File "/var/task/tibanna/check_task.py", line 146, in terminate_idle_instance
    raise EC2IdleException(errmsg)
tibanna.exceptions.EC2IdleException: Nothing has been running for the past hour for job 50GqmF8999zs,but cannot terminate the instance - cpu utilization (0.994791666668486) : Nothing has been running for the past hour for job 50GqmF8999zs,(CPU utilization 0.994791666668486 and EBS read  bytes).
```

...Going through the tibanna logs, I don't see any unusual processes. Here is one of the reports from shortly before the node was killed...

```
top - 14:00:01 up 18:58,  0 users,  load average: 0.00, 0.00, 0.00
Tasks: 343 total,   1 running, 342 sleeping,   0 stopped,   0 zombie
%Cpu(s): 14.5 us,  0.1 sy,  0.0 ni, 85.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 25175464+total, 23983280+free,   921060 used, 11000780 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 24944550+avail Mem

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
129618 root      20   0   70588  22664   4828 S  93.8  0.0   0:00.17 mon-put-i+
129617 root      20   0   70540  22740   4884 S  87.5  0.0   0:00.16 mon-put-i+
  8841 root      20   0 7650268 170588  15624 S  12.5  0.1  86:54.66 python
129614 root      20   0   40652   3884   3196 R   6.2  0.0   0:00.01 top
     1 root      20   0   37968   5968   3956 S   0.0  0.0   0:12.74 systemd
     2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd
     3 root      20   0       0      0      0 S   0.0  0.0   0:00.08 ksoftirqd+
     4 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/0+
```

...My best guess at what may be happening here...

1. Some bug in tibanna is causing the snakemake process to be killed?
2. Some bug in snakemake is causing it to be unable to detect that the busco job finished
3. Some bug in busco is causing the process to only appear to finish and the process is hung for some reason, perhaps due to some interaction with the docker container running both snakemake and singularity or some interaction between busco and singularity.

....I'm trying to hunt down the bug in these three locations. I'd like input on how feasible they are. If snakemake dies unexpectedly, how would tibanna react?

**Comment by nhartwic** [comment]
Update. Further testing suggests that it was a result of an interaction between busco and singularity. Or I just got unreasonably lucky. Hard to say for sure. Basically, as one of my debugging steps I edited my workflow to use conda instead of a dockerhub uri for defining the environment, same busco version, though dependencies of busco may have changed and the effective os may have changed. I'd have to dig into the snakemake docker image to determine if the OS was different. 

In any case when using my dockerhub uri (and singularity via snakemake), I experienced the bug in 3 out of 4 runs. After switching to the conda environment definition, I was able to run all 3 runs without issue. Going from 1/4 to 3/3 isn't a statistically significant difference, but whatevs, I got the results I was after.

Since this bug doesn't seem to be a result of Tibanna, I'm going to close this issue and leave further debugging for the future, if I encounter the bug again.
