### ISSUE TITLE
Tibanna/Snakemake compatibility issue?

### ISSUE THREAD

**Issue by dvav** [4dn-dcic/tibanna#362]
Hi,

I 've been using `Tibanna` with `Snakemake` for some time now without any problem. However, it seems that I cannot make `Tibanna` work with `Snakemake v7.0.0` or higher (see traceback below). It works fine, though, with `Snakemake v6.15.5`. Any idea what's wrong? Maybe it has something to do with `Snakemake v7.0.0` requiring at least `Python v3.7`?        

Many thanks,
Dimitris

```
Traceback (most recent call last):
  File "/home/dimitris/Tmp/test_smk/venv/lib/python3.9/site-packages/snakemake/utils.py", line 430, in format
    return fmt.format(_pattern, *args, **variables)
  File "/usr/lib/python3.9/string.py", line 161, in format
    return self.vformat(format_string, args, kwargs)
  File "/usr/lib/python3.9/string.py", line 165, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/usr/lib/python3.9/string.py", line 205, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "/usr/lib/python3.9/string.py", line 270, in get_field
    obj = self.get_value(first, args, kwargs)
  File "/usr/lib/python3.9/string.py", line 227, in get_value
    return kwargs[key]
KeyError: 'job_specific_args'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dimitris/Tmp/test_smk/venv/lib/python3.9/site-packages/snakemake/__init__.py", line 714, in snakemake
    success = workflow.execute(
  File "/home/dimitris/Tmp/test_smk/venv/lib/python3.9/site-packages/snakemake/workflow.py", line 1097, in execute
    success = self.scheduler.schedule()
  File "/home/dimitris/Tmp/test_smk/venv/lib/python3.9/site-packages/snakemake/scheduler.py", line 540, in schedule
    self.run(runjobs)
  File "/home/dimitris/Tmp/test_smk/venv/lib/python3.9/site-packages/snakemake/scheduler.py", line 588, in run
    executor.run_jobs(
  File "/home/dimitris/Tmp/test_smk/venv/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 153, in run_jobs
    self.run(
  File "/home/dimitris/Tmp/test_smk/venv/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2360, in run
    tibanna_input = self.make_tibanna_input(job)
  File "/home/dimitris/Tmp/test_smk/venv/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2344, in make_tibanna_input
    self.add_command(job, tibanna_args, tibanna_config)
  File "/home/dimitris/Tmp/test_smk/venv/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2221, in add_command
    command = self.format_job_pattern(
  File "/home/dimitris/Tmp/test_smk/venv/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 375, in format_job_pattern
    cmd = format(
  File "/home/dimitris/Tmp/test_smk/venv/lib/python3.9/site-packages/snakemake/utils.py", line 432, in format
    if str(ex).strip("'") in variables["wildcards"].keys():
KeyError: 'wildcards'

```

**Comment by alexander-veit** [comment]
Hi, 
I am not sure what the issue is. I don't think it is related to the Python version. Tibanna should run fine with Python 3.7 and 3.8. It looks more like an issue in Snakemake to me. Maybe you post it there?

**Comment by dvav** [comment]
OK, thank you for your feedback. I 'll post it there, too.

**Comment by nhartwic** [comment]
For whatever its worth, I've also been using snakemake with tibanna. I'm currently on snakemake 7.3.1 and tibanna 1.9.1 and haven't encountered the bug you experienced. Hard to figure out what could be going wrong without more details.

**Comment by dvav** [comment]
Thank you @nhartwic , good to know. I posted the issue on the snakemake site and they fixed the bug in one of their recent releases.
