### ISSUE TITLE
KMS Authentication Error in Lambda When Running Tibanna

### ISSUE THREAD

**Issue by yuji-yoshida-craif** [4dn-dcic/tibanna#402]
After executing the command:
`tibanna deploy_unicorn -g tibanna_group -b bucket`
I proceeded to run:
`tibanna run_workflow --input-json=tibanna_input.json`
However, I encountered an error in the first Lambda function during the Step Function execution:
```
{
  "cause": "Lambda was unable to decrypt the environment variables because KMS access was denied. Please check the function's KMS key settings. KMS Exception: AccessDeniedExceptionKMS Message: User: arn:aws:sts::aws-account:assumed-role/tibanna_a_run_task_awsem/run_task_awsem_tibanna_a is not authorized to perform: kms:Decrypt on resource: arn:aws:kms:resion:aws-acount:key/key_ID because no resource-based policy allows the kms:Decrypt action (Service: Lambda, Status Code: 502, Request ID: ID)",
  "error": "Lambda.KMSAccessDeniedException"
}
```
Could you help identify the cause and suggest a solution?

Here is the input.json I used:
```
{
  "args": {
    "language": "snakemake",
    "snakemake_directory_url": "s3://bucket",
    "snakemake_main_filename": "Snakefile",
    "container_image": "snakemake/snakemake",
    "command": "snakemake --use-conda all",
    "output_S3_bucket": "bucket",
    "input_files": {
      "fastq_files": {
        "bucket_name": "bucket",
        "object_key": "fastq/*.fastq.gz",
        "mount": true
      }
    }
  },
  "config": {
    "log_bucket": "log-bucket",
    "instance_type": ["t3.medium", "t3.small"],
    "mem": 8,
    "mem_as_is": false,
    "cpu": 2,
    "ebs_size": 20,
    "ebs_size_as_is": false,
    "EBS_optimized": true,
    "root_ebs_size": 8,
    "shutdown_min": "now",
    "password": "",
    "key_name": "",
    "ebs_iops": null,
    "ebs_throughput": null,
    "ebs_type": "gp3",
    "spot_instance": false,
    "spot_duration": null,
    "behavior_on_capacity_limit": "fail",
    "availability_zone": "",
    "security_group": "",
    "subnet": ""
  }
}
```

**Comment by alexander-veit** [comment]
It seems you are using server side encryption. Try setting the following environment variable:
```
export S3_ENCRYPT_KEY_ID=<YOUR_KEY_ID>
```
After that you need to redeploy Tibanna.

**Comment by yuji-yoshida-craif** [comment]
Thank you. I implemented that setting, but I encountered the following error. 
It seems that the KEY_ID is associated with an AWS-managed policy, and I am unable to edit the policy. Are there any prerequisites or settings I should configure in S3 beforehand?

```
root# tibanna deploy_unicorn -g tibanna_group -b my-bucket
setting up tibanna usergroup environment on AWS...
Deleting public access block for bucket my-bucket
creating iam permissions with tibanna policy prefix tibanna_tibanna_group
Tibanna usergroup tibanna_group has been created on AWS.
Traceback (most recent call last):
  File "/opt/conda/envs/snakerunner/bin/tibanna", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/snakerunner/lib/python3.11/site-packages/tibanna/__main__.py", line 580, in main
    subcommandf(*sc_args)
  File "/opt/conda/envs/snakerunner/lib/python3.11/site-packages/tibanna/__main__.py", line 424, in deploy_unicorn
    API().deploy_unicorn(suffix=suffix, no_setup=no_setup, buckets=buckets, no_setenv=no_setenv,
  File "/opt/conda/envs/snakerunner/lib/python3.11/site-packages/tibanna/core.py", line 885, in deploy_unicorn
    self.deploy_tibanna(suffix=suffix, usergroup=usergroup, setup=not no_setup,
  File "/opt/conda/envs/snakerunner/lib/python3.11/site-packages/tibanna/core.py", line 845, in deploy_tibanna
    self.cleanup_kms()
  File "/opt/conda/envs/snakerunner/lib/python3.11/site-packages/tibanna/core.py", line 701, in cleanup_kms
    kms_client.put_key_policy(
  File "/opt/conda/envs/snakerunner/lib/python3.11/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/snakerunner/lib/python3.11/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the PutKeyPolicy operation: User: arn:aws:iam::aws-account:user/tibanna_user is not authorized to perform: kms:PutKeyPolicy on resource: arn:aws:kms:ap-northeast-1:aws-account:key/KEY_ID because no resource-based policy allows the kms:PutKeyPolicy action
```

**Comment by yuji-yoshida-craif** [comment]
I'm sorry. I accidentally closed it.
